### ISSUE TITLE
Naming convention for SMD parts is not benefitial for creating footprint filters

### ISSUE THREAD

**Issue by poeschlr** [KiCad/Housings_DIP.pretty#12]
Currently the _SMD is a suffix at the end of the footprint name.
This makes it hard to create footprint filters that allow filtering of optional suffixes without also showing the SMD parts. (Adding a `*` at the end will also show `*_SMD` in the results)

This problem has been encountered in pull request: https://github.com/KiCad/kicad-library/pull/1543

I would suggest to change the naming to `DIP_SMD-[number pins]_W[width]mm_ ...`

**Comment by jkriege2** [comment]
Unfortunetaly this will also not solve the problem, as `DIP*W7.62mm*` does also match `DIP_SMD-8_W7.62mm`. So I would say the only renaming solution seems to me to be `SMDDIP-[pinnumber]_W[width]mm`.

On the other hand the SMD-footprints are not totally wrong (also not totally correct), as you can still bend the pins and solder it onto that footprint (In that sense the footprint can be seen as a variant) ...

So maybe we can also leave it the way it is and rely on people to know the difference between the SMD and non-SMD-version ...? If the SMD is actually required, the SMD can be added to the FPFilter.

Best,
JAN

**Comment by jkriege2** [comment]
@diggit @SchrodingersGat @hackscribble @Shackmeister @evanshultz Do you have input on this?

**Comment by poeschlr** [comment]
Damn you are right. What if we use SMD as a prefix for such parts?
Would then be `SMD_DIP-...`
But i'm not sure if this works in every instance. (Manufacturer prefix)

It would really be nice if we had some other way of filtering then by name.

**Comment by SchrodingersGat** [comment]
SMDIP ?

**Comment by jkriege2** [comment]
I made a PR for the name change: https://github.com/KiCad/Housings_DIP.pretty/pull/15

**Comment by jkriege2** [comment]
footprints have been renamed ... can this be closed?

**Comment by poeschlr** [comment]
I guess yes. Thanks @jkriege2 for the fix and thanks at @SchrodingersGat for the good idea.
